name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Project
        run: ./gradlew clean build
        
      - name: Run Test
        run: ./gradlew clean test
